com.mojang.renderpearl.api.GpuFormat=com.mojang.blaze3d.GpuFormat
com.mojang.renderpearl.api.buffers.GpuBuffer=com.mojang.blaze3d.buffers.GpuBuffer
com.mojang.renderpearl.api.buffers.GpuBufferSlice=com.mojang.blaze3d.buffers.GpuBufferSlice
com.mojang.renderpearl.api.commands.CommandEncoder=com.mojang.blaze3d.systems.CommandEncoder
com.mojang.renderpearl.api.commands.GpuFence=com.mojang.blaze3d.buffers.GpuFence
com.mojang.renderpearl.api.commands.RenderPassDescriptor=com.mojang.blaze3d.systems.RenderPassDescriptor
com.mojang.renderpearl.api.pipeline.BindGroupLayout=com.mojang.blaze3d.pipeline.BindGroupLayout
com.mojang.renderpearl.api.pipeline.BlendFactor=com.mojang.blaze3d.platform.BlendFactor
com.mojang.renderpearl.api.pipeline.BlendOp=com.mojang.blaze3d.platform.BlendOp
com.mojang.renderpearl.api.pipeline.CompareOp=com.mojang.blaze3d.platform.CompareOp
com.mojang.renderpearl.api.pipeline.PrimitiveTopology=com.mojang.blaze3d.PrimitiveTopology
com.mojang.renderpearl.api.textures.GpuSampler=com.mojang.blaze3d.textures.GpuSampler
com.mojang.renderpearl.api.textures.GpuTexture=com.mojang.blaze3d.textures.GpuTexture
com.mojang.renderpearl.api.textures.GpuTextureView=com.mojang.blaze3d.textures.GpuTextureView
com.mojang.renderpearl.backend.api.CommandEncoderBackend=com.mojang.blaze3d.systems.CommandEncoderBackend
com.mojang.renderpearl.api.buffers.TransientMemory=com.mojang.blaze3d.systems.TransientMemory
com.mojang.renderpearl.api.commands.GpuQueryPool=com.mojang.blaze3d.systems.GpuQueryPool
com.mojang.renderpearl.api.commands.RenderPass=com.mojang.blaze3d.systems.RenderPass
com.mojang.renderpearl.backend.api.RenderPassBackend=com.mojang.blaze3d.systems.RenderPassBackend
com.mojang.renderpearl.backend.common.BaseGpuBuffer=com.mojang.blaze3d.buffers.GpuBuffer
com.mojang.renderpearl.backend.common.BaseGpuTexture=com.mojang.blaze3d.textures.GpuTexture
com.mojang.renderpearl.backend.common.BaseGpuTextureView=com.mojang.blaze3d.textures.GpuTextureView
com.mojang.renderpearl.api.pipeline.IndexType=com.mojang.blaze3d.IndexType
