minecraft_version=26.3
fabric_api_version=0.161.0+26.3
sodium_version=mc26.3-0.9.2-fabric
minecraft_dep=~26.3
sodium_dep=>=0.9.2 <0.9.4-alpha
mixins=mcopt-metal,mcopt-metal-qos,mcopt-metal-cpu,mcopt-metal-cpu-ab,mcopt-metal-chunk,mcopt-metal-lod,mcopt-metal-gen,mcopt-metal-gen-noise,mcopt-metal-startup,mcopt-metal-alloc,mcopt-metal-probe,mcopt-metal-chunkio,mcopt-metal-edge,mcopt-metal-lunar
